### ISSUE TITLE
bug: Heatmap::new with incorrect resolution

### ISSUE THREAD

**Issue by l2dy** [iopsystems/rezolus#12]
Potential data resolution issue.

### Expected behavior

In [metriken::Heatmap::new](https://docs.rs/metriken/0.1.3/metriken/struct.Heatmap.html#method.new), the span parameter should be larger than resolution.

### Actual behavior

The span (4th) parameter is 1 second and the resolution parameter is 100 seconds.

https://github.com/iopsystems/rezolus/blob/8634df2e2a3ea83c14fc990a101de333af56ea22/src/common/mod.rs#L111-L131

### Steps to reproduce the behavior

N/A

**Comment by brayniac** [comment]
Good catch. Fixed in #15 

Thanks for reporting

**Comment by l2dy** [comment]
The doc comment for the function says that the heatmap covers a moving window of one minute with one second resolution. Should we use 60 and 1 for span and resolution?

https://github.com/iopsystems/rezolus/blob/1e9bcaa3ba9907f73816275e4b9b47eadc69bd2b/src/common/mod.rs#L109-L110

**Comment by brayniac** [comment]
No. The comment should be updated instead. We are currently focused on use
cases where stats are collected from Rezolus on a secondly basis. We have
changes planned that will enable usage in environments with different
collection intervals. Those who are focused on minutely collection would be
better to use the non-alpha version for the time being.

**Comment by l2dy** [comment]
> No. The comment should be updated instead. We are currently focused on use cases where stats are collected from Rezolus on a secondly basis.

With 1 second span and 100ms resolution, there are 10 samples in the heatmap to calculate percentiles from, which means anything above p90 would be an estimate. Is it expected to get p9999 from just 10 samples?

https://github.com/iopsystems/rezolus/blob/2f57faf6514dd6681e1a7649c2deb91c53de7a6c/src/main.rs#L22-L24

**Comment by brayniac** [comment]
Not entirely correct.

The p99.9+ will currently be the max sample in the histogram for metrics
that are taken from counters and gauges. We sample on 10ms interval, which
means each 100ms histogram within the heatmap has 10 samples. But the
heatmap is a collection of histograms and covers a 1s span. So we have 100
samples per heatmap for counter/gauge metrics. The percentiles are reported
across this 1s span.

For counters, the values in the heatmap are really the average rate across
10ms windows. The p99.9+ will report the highest of those rates in the past
second. The p99 will be the second highest. And so on.

The downside to using a 60s window if we're collecting on a secondly basis
is that everything is dampened. It takes some time for lower percentiles to
begin to reflect the new state of the system. They would indeed still be
the percentile across the last minute, but if we have the luxury of
sampling on a secondly basis, they can move too slowly to correlate with
secondly request/s metrics.

Now, for things like block io latency and scheduler runqueue latency, since
they are based on individual events it would depend on how many events
there were in that second. For these metrics, we should find that there are
many events for the metrics we care about for particular workloads. For
example, if we're focused on a service like an in-memory cache, we
anticipate having many many requests per second, probably using TCP, so
those BPF based metrics will be pulling from heatmap with many thousands of
events.

But we can actually imagine the opposite too, such a workload (assuming
logging is disabled and there isn't much background activity on the host)
would not generate much disk io. So our block io size distributions might
only have a few operations in the 1s heatmap span.

We actually see the same with request latency metrics in load generator or
service reported latencies. The true load might be low enough that the
upper percentiles effectively reflect the max.

Issue #10 is open for us to revisit the parameters, but for our current
use-case where we are sampling on a secondly basis, we are prioritizing
having more responsive percentiles meaning we must use shorter heatmap
spans.

Hopefully this explanation gives you a bit more context for the trade-offs
we have picked for the time being, and some more insight into the behavior
and meaning of the percentiles.

**Comment by l2dy** [comment]
Thanks a lot for the detailed explanation. At this precision, dampening effect is real and your choice sounds reasonable.

I don't have the luxury of collecting metrics at second-level precision, but the non-alpha version has too much code for me to grasp quickly, so I'm going to modify the interval values in my personal fork until collection intervals is made configurable.

I actually misunderstood how Histogram works in the `heatmap` crate and thought only 10 samples were used. With 100 samples in the span, p9999 would be equal to p999 which is supposed to be the maximum value. Should p9999 be removed then?

**Comment by brayniac** [comment]
Sure, glad it helps. The alpha isn't really intended for wide use. I'd
expect you'll see breaking changes as we refine things and get ready for a
release. But hopefully it helps you in the meantime.

No, we shouldn't remove p9999 because p9999 is still useful for things
sourced from distributions. We currently don't know the metric provenance
at the point of exposition. We only know if we're reading from a heatmap,
but don't know if it's counter rates, gauge readings, or a distribution of
event metrics (eg block io size distributions). I think that currently
having a duplicate for those series is worth the cost so we can easily get
the tail latencies for scheduler runqueue latency. I intend to address this
as part of issue #10.
